### ISSUE TITLE
Replace input and history

### ISSUE THREAD

**Issue by claudiocabral** [claudiocabral/42sh#2]
Input and history are seriously broken, they need to be completely replaced or rewritten.

**Comment by claudiocabral** [comment]
@yzalbj quand je quite avec `ctrl-d` le cursur ne reviens pas.
Je suis dans arch linux avec rxvt-unicode, et j'ai constaté le même souci dans l'ordi de @iomonad, tu peux regarder ça?

**Comment by iomonad** [comment]
:+1: le curseur est k-c sous linux

**Comment by claudiocabral** [comment]
cool, maintenant c'est bon :)
Est-ce que tu vas rajouter des keybindings style e-macs? Comme ça on a dejà 1 bonus
